using System.IO;
using UnityEngine;

namespace Game.Config.Model
{
    public static class ConfigPaths
    {
        public static string IndexFileName = "index.json";
        //Generation paths
        public static readonly string AutogeneratedCodePath = Path.Combine(Application.dataPath, "Autogenerated/Config/");
        public static readonly string ConfigModelClassPath = Path.Combine(AutogeneratedCodePath, "Classes");
        public static readonly string EditorConfigModelPath = Path.Combine(Application.dataPath, "../Temp/Config/Json/");

#if UNITY_ANDROID && !UNITY_EDITOR
        public static readonly string LocalAssetPath = Path.Combine("jar:file://" + Application.dataPath + "!/assets", "Config/Data/");
#else
        public static readonly string LocalAssetPath = Path.Combine(Application.streamingAssetsPath, "Config/Data/");
#endif
        public static readonly string LocalIndexFile = Path.Combine(LocalAssetPath, IndexFileName);

        // the Cached and S3 paths are in the ConfigAdminClass as they need internal info to get the right version.
    }
}