//
// AUTOGENERATED - DO NOT MODIFY.
//

namespace Game.Config.Model
{
    public class CastleStatsModel : IConfigModel
    {
        public string Id => id;
        public float WallHp => wallHp;
        public float IncomeRate => incomeRate;
        public float IncomeCapacity => incomeCapacity;
        public int ArchersNumber => archersNumber;
        public float ArchersDamage => archersDamage;


        protected string id;
        protected float wallHp;
        protected float incomeRate;
        protected float incomeCapacity;
        protected int archersNumber;
        protected float archersDamage;

    }
}