//
// AUTOGENERATED - DO NOT MODIFY.
//

namespace Game.Config.Model
{
    public class CastlePricesModel : IConfigModel
    {
        public string Id => id;
        public int WallHp => wallHp;
        public int IncomeRate => incomeRate;
        public int IncomeCapacity => incomeCapacity;
        public int ArchersNumber => archersNumber;
        public int ArchersDamage => archersDamage;


        protected string id;
        protected int wallHp;
        protected int incomeRate;
        protected int incomeCapacity;
        protected int archersNumber;
        protected int archersDamage;

    }
}