//
// AUTOGENERATED - DO NOT MODIFY.
//

namespace Game.Config.Model
{
    public class EnemyUpgradesModel : IConfigModel
    {
        public string Id => id;
        public float MinionHealth => minionHealth;
        public float MinionDamage => minionDamage;
        public float WarriorHealth => warriorHealth;
        public float WarriorDamage => warriorDamage;
        public float BruteHealth => bruteHealth;
        public float BruteDamage => bruteDamage;


        protected string id;
        protected float minionHealth;
        protected float minionDamage;
        protected float warriorHealth;
        protected float warriorDamage;
        protected float bruteHealth;
        protected float bruteDamage;

    }
}