//
// AUTOGENERATED - DO NOT MODIFY.
//

namespace Game.Config.Model
{
    public class ExpModel : IConfigModel
    {
        public string Id => id;
        public int Exp => exp;


        protected string id;
        protected int exp;

    }
}