//
// AUTOGENERATED - DO NOT MODIFY.
//

namespace Game.Config.Model
{
    public class GameSettingsModel : IConfigModel
    {
        public string Id => id;
        public int ExpForUpgrade => expForUpgrade;


        protected string id;
        protected int expForUpgrade;

    }
}