//
// AUTOGENERATED - DO NOT MODIFY.
//

namespace Game.Config.Model
{
    public class SpellsStatsModel : IConfigModel
    {
        public string Id => id;
        public float FireballSize => fireballSize;
        public float FireballDamage => fireballDamage;
        public float LaserDps => laserDps;
        public float LightningSize => lightningSize;
        public float LightningDamage => lightningDamage;
        public float LightningDuration => lightningDuration;
        public float AcidSize => acidSize;
        public float AcidDps => acidDps;
        public float AcidDuration => acidDuration;
        public float GasSize => gasSize;
        public float GasDps => gasDps;
        public float GasDuration => gasDuration;
        public float WindDps => windDps;
        public float WindSpeed => windSpeed;
        public float SummonDamage => summonDamage;
        public float SummonSpeed => summonSpeed;
        public float SummonDuration => summonDuration;
        public float HoleSize => holeSize;
        public float HoleDamage => holeDamage;
        public float HoleDuration => holeDuration;


        protected string id;
        protected float fireballSize;
        protected float fireballDamage;
        protected float laserDps;
        protected float lightningSize;
        protected float lightningDamage;
        protected float lightningDuration;
        protected float acidSize;
        protected float acidDps;
        protected float acidDuration;
        protected float gasSize;
        protected float gasDps;
        protected float gasDuration;
        protected float windDps;
        protected float windSpeed;
        protected float summonDamage;
        protected float summonSpeed;
        protected float summonDuration;
        protected float holeSize;
        protected float holeDamage;
        protected float holeDuration;

    }
}