//
// AUTOGENERATED - DO NOT MODIFY.
//

namespace Game.Config.Model
{
    public class SpellsUnlockModel : IConfigModel
    {
        public string Id => id;
        public int Level => level;


        protected string id;
        protected int level;

    }
}