//
// AUTOGENERATED - DO NOT MODIFY.
//

namespace Game.Config.Model
{
    public class SpellsPricesModel : IConfigModel
    {
        public string Id => id;
        public int FireballSize => fireballSize;
        public int FireballDamage => fireballDamage;
        public int LaserDps => laserDps;
        public int LightningSize => lightningSize;
        public int LightningDamage => lightningDamage;
        public int LightningDuration => lightningDuration;
        public int AcidSize => acidSize;
        public int AcidDps => acidDps;
        public int AcidDuration => acidDuration;
        public int GasSize => gasSize;
        public int GasDps => gasDps;
        public int GasDuration => gasDuration;
        public int WindDps => windDps;
        public int WindSpeed => windSpeed;
        public int SummonDamage => summonDamage;
        public int SummonSpeed => summonSpeed;
        public int SummonDuration => summonDuration;
        public int HoleSize => holeSize;
        public int HoleDamage => holeDamage;
        public int HoleDuration => holeDuration;


        protected string id;
        protected int fireballSize;
        protected int fireballDamage;
        protected int laserDps;
        protected int lightningSize;
        protected int lightningDamage;
        protected int lightningDuration;
        protected int acidSize;
        protected int acidDps;
        protected int acidDuration;
        protected int gasSize;
        protected int gasDps;
        protected int gasDuration;
        protected int windDps;
        protected int windSpeed;
        protected int summonDamage;
        protected int summonSpeed;
        protected int summonDuration;
        protected int holeSize;
        protected int holeDamage;
        protected int holeDuration;

    }
}